Fix: SubjectReceiver: use safe navigation for sharedToken
When sharedToken is null (possibly a misconfigured IdP), Validator Service
blows up with an Internal Error, with stack trace pointing to the missing sharedToken value:

    NoMethodError (undefined method `to_sym' for nil:NilClass):

    lib/authentication/subject_receiver.rb:30:in `block in subject'
    lib/authentication/subject_receiver.rb:25:in `subject'
    lib/authentication/subject_receiver.rb:12:in `receive'

Fix this by using safe navigation - which results into the default empty set of permissions being used.